# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20160701_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='weight',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
