# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_auto_20160701_1513'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='block',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
