# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_auto_20160702_2248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
    ]
