# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0006_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
