# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0008_auto_20160719_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='newsemail',
        ),
    ]
