# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0009_auto_20160722_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='sidebar',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('arxiki1', '\u0391\u03c1\u03c7\u03b9\u03ba\u03b7 1'), ('arxiki2', '\u0391\u03c1\u03c7\u03b9\u03ba\u03b7 2'), ('arxiki3', '\u0391\u03c1\u03c7\u03b9\u03ba\u03b7 3'), ('arxikipano', '\u0391\u03c1\u03c7\u03b9\u03ba\u03b7 \u03c0\u03b1\u03bd\u03c9')], default='right', max_length=10),
        ),
    ]
