# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0010_auto_20160722_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prognostika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodikos', models.CharField(max_length=500)),
                ('agonas', models.CharField(max_length=500)),
                ('apodosi', models.CharField(max_length=500)),
                ('simeio', models.CharField(max_length=500)),
                ('apotelesma', models.CharField(max_length=500)),
                ('bookmaker_link', models.CharField(max_length=500)),
                ('bookmaker_title', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sport', models.CharField(choices=[('football', '\u03a0\u03bf\u03b4\u03cc\u03c3\u03c6\u03b1\u03b9\u03c1\u03bf'), ('basketball', '\u039c\u03c0\u03ac\u03c3\u03ba\u03b5\u03c4'), ('tennis', '\u03a4\u03ad\u03bd\u03bd\u03b9\u03c2'), ('volley', '\u0392\u03cc\u03bb\u03bb\u03b5\u03c5')], default='football', max_length=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
