# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0011_prognostika'),
    ]

    operations = [
        migrations.AddField(
            model_name='prognostika',
            name='xroma',
            field=models.CharField(choices=[('nulls', '\u039a\u03b1\u03bd\u03ad\u03bd\u03b1'), ('kerdismeno', '\u039a\u03b5\u03c1\u03b4\u03b9\u03c3\u03bc\u03ad\u03bd\u03bf'), ('xameno', '\u03a7\u03b1\u03bc\u03ad\u03bd\u03bf')], default='nulls', max_length=10),
        ),
    ]
